# Generated by Django 4.2.5 on 2023-10-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_publicacion_rename_usuario_user_delete_scorebar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='compartidos',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='description',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='shared',
            field=models.IntegerField(default=0),
        ),
    ]
